# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_calculationquestion_imagey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculationquestion',
            name='imagey',
        ),
        migrations.AddField(
            model_name='calculationquestion',
            name='imager',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
